-
  name: create mso schema
  hosts: localhost
  tasks:
    - include_vars: mso_variables.yml

    - name: Set vars
      set_fact: 
        mso_info: &mso_info
          host: '{{ mso_host }}'
          username: '{{ mso_user }}'
          password: '{{ mso_password }}'
          validate_certs: no


    - name: Add cloud template
      cisco.mso.mso_schema_template:
        <<: *mso_info
        tenant: hybrid_dom
        schema: hybrid application
        template: cloud
        state: present
      delegate_to: localhost


    - name: Add cloud template to cloud sites
      cisco.mso.mso_schema_site:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        state: present
        site: Azure
      delegate_to: localhost


    - name: Add hybrid template
      cisco.mso.mso_schema_template:
        <<: *mso_info
        tenant: hybrid_dom
        schema: hybrid application
        template: hybrid
        state: present
      delegate_to: localhost


    - name: Add a new VRF to hybrid template
      cisco.mso.mso_schema_template_vrf:
        <<: *mso_info
        schema: hybrid application
        template: hybrid
        vrf: tfvrf1
        state: present
      delegate_to: localhost


    - name: Add a new site VRF CIDR to Azure
      cisco.mso.mso_schema_site_vrf_region_cidr:
        <<: *mso_info
        schema: hybrid application
        template: hybrid
        vrf: tfvrf1
        state: present
        site: '{{ Azure_site }}'
        region: francecentral
        cidr: '{{ cidr_azure }}'
        primary: true
      delegate_to: localhost
      register: cm_add_cidr

    - name: Add hub network in tfvrf1 region francecentral at Azure site level
      cisco.mso.mso_schema_site_vrf_region_hub_network:
        <<: *mso_info
        schema: hybrid application
        template: hybrid
        site: '{{Azure_site}}'
        vrf: tfvrf1
        region: francecentral
        hub_network:
          name: default
          tenant: infra
        state: present

    - name: Add a new site VRF region CIDR subnet for Azure
      cisco.mso.mso_schema_site_vrf_region_cidr_subnet:
        <<: *mso_info
        schema: hybrid application
        template: hybrid
        site: '{{ Azure_site }}'
        vrf: tfvrf1
        cidr: '{{ item.cidr }}'
        subnet: '{{ item.subnet }}'
        state: present
        region: '{{ item.zone }}'
      delegate_to: localhost
      loop: '{{ subnetsAzure }}'          

    - name: Remove VPN Gateway Router at Region for Azure
      cisco.mso.mso_schema_site_vrf_region:
        <<: *mso_info
        schema: hybrid application
        template: hybrid
        site: '{{ Azure_site }}'
        vrf: tfvrf1
        region: francecentral
        vpn_gateway_router: false
        state: present


    - name: Add hybrid template to all sites
      cisco.mso.mso_schema_site:
        <<: *mso_info
        schema: hybrid application
        template: hybrid
        state: present
        site: Azure
      delegate_to: localhost


    - name: create ANP for cloud 
      mso_schema_template_anp:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        state: present
        anp: cloudAP


    - name: Add Filter 1 exist
      mso_schema_template_filter_entry:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        filter: Filter1
        entry: Filter1-Entry
        state: present

    - name: Ensure Contract1 exist
      mso_schema_template_contract_filter: &contract_present
        <<: *mso_info
        schema: hybrid application
        template: cloud
        contract: Contract1
        filter: Filter1
        filter_schema: hybrid application
        state: present
    

    - name: Add EPG to cloud ANP
      mso_schema_template_anp_epg:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        anp: cloudAP
        epg: web
        vrf:
          name: tfvrf1
          template: hybrid
        state: present

    - name: Add EPG to cloud ANP
      mso_schema_template_anp_epg:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        anp: cloudAP
        epg: db
        vrf:
          name: tfvrf1
          template: hybrid
        state: present



    - name: Add a selector to Azure external EPG
      cisco.mso.mso_schema_site_external_epg_selector:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        site: '{{ Azure_site }}'
        external_epg: internet
        selector: internet
        expressions:
          - type: ip_address
            operator: equals
            value: 0.0.0.0/0
        state: present


    # ADD external EPG
    - name: Add external EPG cloud
      cisco.mso.mso_schema_template_external_epg:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        external_epg: internet
        type: cloud
        anp: 
          name: cloudAP
          template: cloud
        vrf:
          name: tfvrf1
          template: hybrid
        state: present



    # ADD Contract to EPG
    - name: Add Contract1 to EPG web
      cisco.mso.mso_schema_template_anp_epg_contract:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        anp: cloudAP
        epg: web
        contract:
          name: Contract1
          type: '{{ item }}'
        state: present
      loop:
        - 'consumer'
        - 'provider'

    - name: Add Contract1 to EPG db
      cisco.mso.mso_schema_template_anp_epg_contract: 
        <<: *mso_info
        schema: hybrid application
        template: cloud
        anp: cloudAP
        epg: db
        contract:
          name: Contract1
          type: '{{ item }}'
        state: present
      loop:
        - 'consumer'
        - 'provider'


    # ADD Contract to External EPG
    - name: Add Contract1 to External EPG
      cisco.mso.mso_schema_template_external_epg_contract:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        external_epg: internet
        contract:
          name: Contract1
          type: '{{ item }}'
        state: present
      loop:
        - 'consumer'
        - 'provider'
    
    - name: Add Selector to EPG web
      cisco.mso.mso_schema_site_anp_epg_selector:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        anp: cloudAP
        epg: web
        site: '{{item}}'
        selector: web
        expressions:
          - type: application
            operator: equals
            value: web
        state: present
      delegate_to: localhost
      loop: '{{ cloud_sites }}'

    - name: Add Selector to EPG db
      cisco.mso.mso_schema_site_anp_epg_selector:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        anp: cloudAP
        epg: db
        site: '{{item}}'
        selector: db
        expressions:
          - type: application
            operator: equals
            value: db
        state: present
      delegate_to: localhost
      loop: '{{ cloud_sites }}'

